# Generated by Django 5.2.8 on 2026-01-16 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('cifnif', models.CharField(max_length=20)),
                ('client_adress', models.CharField(max_length=150)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Base imponible', max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, help_text='IVA total', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Importe total', max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], default='DRAFT', verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Concepto facturado', max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario sin IVA', max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoices')),
            ],
        ),
    ]
