# Generated by Django 5.2.8 on 2026-01-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='base_amount',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='vat_amount',
        ),
    ]
