# Generated by Django 5.2.8 on 2025-11-21 18:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('club deportivo', 'Club deportivo'), ('colegio', 'Colegio'), ('ayuntamiento', 'Ayuntamiento'), ('universidad', 'Universidad'), ('empresa', 'Empresa'), ('particular', 'Particular')], verbose_name='Tipo de Cliente')),
                ('t_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº teléfono')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Otra información')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('cargo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cargo')),
                ('t_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº teléfono')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionados', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/clients/', verbose_name='Archivos')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion de archivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación de archivo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clients.client')),
            ],
        ),
    ]
