# Generated by Django 5.2.8 on 2025-11-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cif_nif',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='clients_files', verbose_name='Archivos'),
        ),
    ]
