# Generated by Django 5.2.8 on 2025-12-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_cif_nif_alter_clientfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cif_nif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CIF/NIF'),
        ),
    ]
