# Generated by Django 5.2.8 on 2025-12-13 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_cif_nif'),
        ('products', '0005_product_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descripcion corta del Pedido', max_length=50, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibido'), ('PENDING_DESIGN', 'Pendiente de diseño'), ('DESIGN_READY', 'Diseño confirmado'), ('IN_PRODUCTION', 'En producción'), ('COMPLETED', 'Terminado'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING_DESIGN', verbose_name='Estado')),
                ('order_type', models.CharField(choices=[('LARGE', 'Encargo Importante'), ('SMALL', 'Encargo de Mostrador')], verbose_name='Tipo de pedido')),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDesignFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/designs/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_files', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario sin IVA', max_digits=10, verbose_name='Precio presupuestado')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productvariant')),
            ],
        ),
    ]
