# Generated by Django 5.2.8 on 2026-01-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Recibido'), ('PENDING_DESIGN', 'Pendiente de diseño'), ('DESIGN_READY', 'Diseño confirmado'), ('IN_PRODUCTION', 'En producción'), ('COMPLETED', 'Completado'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING_DESIGN', verbose_name='Estado'),
        ),
    ]
