# Generated by Django 5.2.8 on 2026-01-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sent_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
