# Generated by Django 5.2.8 on 2025-12-03 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='Modelo del Producto')),
                ('sku', models.CharField(blank=True, help_text='Referencia interna (opcional)', max_length=50)),
                ('allowed_print', models.CharField(choices=[('DTF', 'DTF'), ('NONE', 'Sin personalización')], default='DTF', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/products_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=30)),
                ('sku', models.CharField(blank=True, help_text='Referencia interna (opcional)', max_length=50)),
                ('stock', models.IntegerField(default=0, help_text='Stock opcional por variante')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'ordering': ['product', 'color', 'size'],
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
