# Generated by Django 5.2.8 on 2025-12-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('TSHIRT', 'Camiseta'), ('HOODIE', 'Sudadera'), ('PANTS', 'Pantalón'), ('OTHER', 'Otros')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
