# Generated by Django 5.2.8 on 2025-12-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='model_url',
        ),
    ]
